### ISSUE TITLE
Missing .yamllint

### ISSUE THREAD

**Issue by coaxial** [coaxial/generator-molecule-lxd-role#16]
Contents:

```yaml
extends: default

rules:
  braces:
    max-spaces-inside: 1
    level: error
  brackets:
    max-spaces-inside: 1
    level: error
  line-length: disable
```
