### ISSUE TITLE
Debian and Ubuntu versions are not separated in the meta file

### ISSUE THREAD

**Issue by coaxial** [coaxial/generator-molecule-lxd-role#26]
```
platforms:
  - name: ubuntu
    version:
      - xenial
      - stretch
```

`stretch` should be under debian instead.
